group:
  # providers
  - files:
      - source: workflows/plain
        dest: .github/workflows/
        deleteOrphaned: true
    repos: |
      cloudquery-policies/aws
      cloudquery-policies/azure
      cloudquery-policies/gcp
      cloudquery-policies/k8s
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-template
      cloudquery/cq-provider-terraform



# core
cloudquery/cloudquery:
  - source: workflows/common
    dest: .github/workflows/
  - .github/release.yml
  - source: dependabot.yml
    dest: .github/dependabot.yml

cloudquery/helm-charts:
  - source: workflows/common/
    dest: .github/workflows/
    exclude: |
      lint_golang.yml

cloudquery/cq-provider-sdk:
  - source: workflows/common
    dest: .github/workflows/
  - .github/release.yml

group:
  # providers
  - files:
      - source: workflows/common
        dest: .github/workflows/
      - source: workflows/providers
        dest: .github/workflows/
      - .github/release.yml
      - source: providers.golangci.yml
        dest: .golangci.yml
      - source: dependabot.yml
        dest: .github/dependabot.yml
      - source: CODEOWNERS
        dest: CODEOWNERS
    repos: |
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-template
      cloudquery/cq-provider-terraform

  # providers with terraform
  - files:
      - source: workflows/terraform
        dest: .github/workflows/
    repos: |
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-azure

  # policies
  - files:
      - source: workflows/common/
        dest: .github/workflows/
        exclude: |
          lint_golang.yml
      - source: workflows/policies
        dest: .github/workflows
      - .github/release.yml
    repos: |
      cloudquery-policies/aws
      cloudquery-policies/gcp
      cloudquery-policies/azure
      cloudquery-policies/k8s
