name: Auto Assign to Project(s)

on:
  issues:
    types: [opened, labeled]
  issue_comment:
    types: [created]
env:
  MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    name: Assign to One Project
    steps:
    - name: Assign all issues to project
      uses: srggrs/assign-one-project-github-action@1.3.1
      with:
        project: 'https://github.com/orgs/cloudquery/projects/2'
        column_name: 'Triage'
